name: .NET Tests with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.7'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Download coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: ./TestResults

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator@v5.1.23
        with:
          reports: './TestResults/*/coverage.cobertura.xml'
          targetdir: './coverage-report'
          reporttypes: 'Html'

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report

      - name: Check coverage threshold
        run: |
          dotnet tool install --global coverlet.console
          export PATH="$PATH:/home/runner/.dotnet/tools"
          coverlet ./path/to/your/test/project/bin/Debug/net7.0/YourTestProject.dll \
            --target "dotnet" \
            --targetargs "test --no-build" \
            --threshold 30 \
            --threshold-type line
