name: .NET Tests with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.302'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build TicTacToeAPI.sln --configuration Debug --no-restore

      - name: Run tests with coverage
        run: dotnet test TicTacToe.Tests/TicTacToe.Tests.csproj --configuration Debug --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Download coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: ./TestResults

      - name: Install ReportGenerator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: |
          export PATH="$PATH:/home/runner/.dotnet/tools"
          reportgenerator -reports:'./TestResults/*/coverage.cobertura.xml' -targetdir:'./coverage-report' -reporttypes:Html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report

      - name: Check coverage threshold
        run: |
          dotnet tool install --global coverlet.console
          export PATH="$PATH:/home/runner/.dotnet/tools"
          coverlet ./TicTacToe.Tests/bin/Debug/net9.0/TicTacToe.Tests.dll \
            --target "dotnet" \
            --targetargs "test --no-build --configuration Debug" \
            --threshold 30 \
            --threshold-type line \
            --exclude-by-file "**/TicTacToeApi/**" \
            --exclude-by-file "**/Infrastructure/**"

